# Generated by Django 2.1.5 on 2019-03-01 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=100)),
                ('no_telepon', models.CharField(max_length=30)),
                ('subyek', models.CharField(max_length=200)),
                ('pesan', models.TextField()),
            ],
        ),
    ]
